name: CD

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt -v

      - name: Run deployment script
        run: |
          if [ "$APP_ENV" == "Dev" ]; then
            echo "Running Dev deployment script..."
            # Add your Dev deployment commands here
          elif [ "$APP_ENV" == "QA" ]; then
            echo "Running QA deployment script..."
            # Add your QA deployment commands here
          elif [ "$APP_ENV" == "Prod" ]; then
            echo "Running Production deployment script..."
            # Add your Production deployment commands here
          fi

      - name: Notify deployment success
        run: echo "Deployment to $APP_ENV successful!"